<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        date_default_timezone_set('Asia/Jakarta');

        DB::table('barang')->insert([
            [
                'nama_barang'           => 'Lacto-B',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+500 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-79 days')),
                'supplier_id'           => 2,
                'stok'                  => 10,
                'satuan_id'             => 4,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 8500,
                'satuan_jual'           => 'Sachet',
                'minimal_stok'          => 10,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Teosal',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+200 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-189 days')),
                'supplier_id'           => 2,
                'stok'                  => 7,
                'satuan_id'             => 4,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 3000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Refaquin',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+438 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-67 days')),
                'supplier_id'           => 2,
                'stok'                  => 1,
                'satuan_id'             => 1,
                'isi'                   => 1,
                'bentuk_id'                => 1,
                'harga_jual'            => 68000,
                'satuan_jual'           => 'Tube',
                'minimal_stok'          => 1,
                'kategori_id'           => 4,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'OBH Combi Plus 100ml',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+20 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-567 days')),
                'supplier_id'           => 2,
                'stok'                  => 5,
                'satuan_id'             => 2,
                'isi'                   => 1,
                'bentuk_id'                => 1,
                'harga_jual'            => 22500,
                'satuan_jual'           => 'Botol',
                'minimal_stok'          => 1,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Alpara',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+189 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-83 days')),
                'supplier_id'           => 4,
                'stok'                  => 40,
                'satuan_id'             => 4,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 8000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Sanmol',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+238 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('129 days')),
                'supplier_id'           => 2,
                'stok'                  => 1,
                'satuan_id'             => 4,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 8000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 1,
                'kategori_id'           => 4,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Vitamin C',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+189 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-312 days')),
                'supplier_id'           => 3,
                'stok'                  => 35,
                'satuan_id'             => 3,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 3000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 1,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Betadine Gargle 190ml',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+28 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-453 days')),
                'supplier_id'           => 1,
                'stok'                  => 8,
                'satuan_id'             => 3,
                'isi'                   => 1,
                'bentuk_id'                => 2,
                'harga_jual'            => 32000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 1,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Alprazolam 0,5 MG',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+387 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-38 days')),
                'supplier_id'           => 6,
                'stok'                  => 25,
                'satuan_id'             => 5,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 120000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 1,
                'golongan_id'           => 1,
            ],
            [
                'nama_barang'           => 'Codeine 10 MG',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+479 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-47 days')),
                'supplier_id'           => 6,
                'stok'                  => 10,
                'satuan_id'             => 5,
                'isi'                   => 10,
                'bentuk_id'                => 1,
                'harga_jual'            => 50000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 1,
                'kategori_id'           => 1,
                'golongan_id'           => 2,
            ],
            
        ]);
    }
}
