<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        date_default_timezone_set('Asia/Jakarta');

        DB::table('barang')->insert([
            // [
            //     'nama_barang'           => 'Lacto-B',
            //     'supplier_id'           => 1,
            //     'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+20 days')),
            //     'tanggal_masuk'         => date('Y-m-d', strtotime('-20 days')),
            //     'jumlah'                => 5,
            //     'satuan_id'             => 4,
            //     'isi'                   => 50,
            //     'bentuk_id'             => 2,
            //     'harga_beli'            => 500000,
            //     'harga_jual'            => 5000,
            //     'satuan_jual'           => 'Strip',
            //     'minimal_stok'          => 10,
            //     'kategori_id'           => 1,
            //     'golongan_id'           => 4,
            // ],
            // [
            //     'nama_barang'           => 'Rhinos',
            //     'supplier_id'           => 1,
            //     'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+20 days')),
            //     'tanggal_masuk'         => now(),
            //     'jumlah'                => 3,
            //     'satuan_id'             => 4,
            //     'isi'                   => 30,
            //     'bentuk_id'             => 2,
            //     'harga_beli'            => 300000,
            //     'harga_jual'            => 3000,
            //     'satuan_jual'           => 'Strip',
            //     'minimal_stok'          => 10,
            //     'kategori_id'           => 1,
            //     'golongan_id'           => 4,
            // ],
        [
            'nama_barang'           => 'Lacto-B',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+25 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-200 days')),
                'jumlah'                => 2,
                'satuan_id'             => 4,
                'isi'                   => 80,
                'bentuk_id'             => 1,
                'harga_beli'            => 15000,
                'harga_jual'            => 5000,
                'satuan_jual'           => 'Sachet',
                'minimal_stok'          => 5,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Refaquin',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+20 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-100 days')),
                'jumlah'                => 3,
                'satuan_id'             => 1,
                'isi'                   => 3,
                'bentuk_id'             => 5,
                'harga_beli'            => 68000,
                'harga_jual'            => 68000,
                'satuan_jual'           => 'Tube',
                'minimal_stok'          => 1,
                'kategori_id'           => 4,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Alpara',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+50 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-129 days')),
                'jumlah'                => 15,
                'satuan_id'             => 4,
                'isi'                   => 223,
                'bentuk_id'             => 7,
                'harga_beli'            => 83000,
                'harga_jual'            => 8000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 15,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Fasidol',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+100 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-80 days')),
                'jumlah'                => 5,
                'satuan_id'             => 4,
                'isi'                   => 50,
                'bentuk_id'             => 7,
                'harga_beli'            => 20000,
                'harga_jual'            => 4000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Zensoderm',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+20 days')),
                'tanggal_masuk'         => now(),
                'jumlah'                => 60,
                'satuan_id'             => 4,
                'isi'                   => 60,
                'bentuk_id'             => 5,
                'harga_beli'            => 4500,
                'harga_jual'            => 8000,
                'satuan_jual'           => 'Tube',
                'minimal_stok'          => 5,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Bioplacenton',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+50 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-20 days')),
                'jumlah'                => 12,
                'satuan_id'             => 1,
                'isi'                   => 12,
                'bentuk_id'             => 10,
                'harga_beli'            => 22800,
                'harga_jual'            => 30000,
                'satuan_jual'           => 'Tube',
                'minimal_stok'          => 2,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Norpid',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+90 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-20 days')),
                'jumlah'                => 10,
                'satuan_id'             => 4,
                'isi'                   => 50,
                'bentuk_id'             => 6,
                'harga_beli'            => 15000,
                'harga_jual'            => 5000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 5,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Hufagrip Flu dan Batuk',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+100 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-98 days')),
                'jumlah'                => 20,
                'satuan_id'             => 3,
                'isi'                   => 20,
                'bentuk_id'             => 2,
                'harga_beli'            => 18500,
                'harga_jual'            => 23000,
                'satuan_jual'           => 'Botol',
                'minimal_stok'          => 1,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Mycoral',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+120 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-98 days')),
                'jumlah'                => 1,
                'satuan_id'             => 4,
                'isi'                   => 5,
                'bentuk_id'             => 6,
                'harga_beli'            => 160000,
                'harga_jual'            => 5500,
                'satuan_jual'           => 'Butir',
                'minimal_stok'          => 10,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Betadine Gargle 190ml',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+74 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('+-98 days')),
                'jumlah'                => 5,
                'satuan_id'             => 4,
                'isi'                   => 5,
                'bentuk_id'             => 2,
                'harga_beli'            => 28000,
                'harga_jual'            => 32000,
                'satuan_jual'           => 'Botol',
                'minimal_stok'          => 1,
                'kategori_id'           => 3,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Gasela',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+198 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-23 days')),
                'jumlah'                => 10,
                'satuan_id'             => 4,
                'isi'                   => 100,
                'bentuk_id'             => 6,
                'harga_beli'            => 18000,
                'harga_jual'            => 4000,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 1,
                'kategori_id'           => 9,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Amlodipine 5mg',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+69 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('+20 days')),
                'jumlah'                => 20,
                'satuan_id'             => 4,
                'isi'                   => 200,
                'bentuk_id'             => 6,
                'harga_beli'            => 24500,
                'harga_jual'            => 4500,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 1,
                'golongan_id'           => 4,
            ],
            [
                'nama_barang'           => 'Vitamin C',
                'tanggal_kedaluwarsa'   => date('Y-m-d', strtotime('+1 days')),
                'tanggal_masuk'         => date('Y-m-d', strtotime('-101 days')),
                'jumlah'                => 10,
                'satuan_id'             => 4,
                'isi'                   => 100,
                'bentuk_id'             => 2,
                'harga_beli'            => 8000,
                'harga_jual'            => 2500,
                'satuan_jual'           => 'Strip',
                'minimal_stok'          => 10,
                'kategori_id'           => 1,
                'golongan_id'           => 4,
            ],
        ]);
    }
}
